/* ==========================================
 * TABLE: GCG_4612_QA_DATA
 * ========================================== */
CREATE TABLE "GCG_4612_QA_DATA"(
 "WO" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "HOLD_COUNT" LONGVARCHAR,
 "RW_COUNT" LONGVARCHAR,
 "RW_NOTES" LONGVARCHAR,
 "RW_CODES" LONGVARCHAR,
 "RT_COUNT" LONGVARCHAR,
 "CAR_NOTES" LONGVARCHAR,
 "RT_CODES" LONGVARCHAR,
 "MRB_COUNT" LONGVARCHAR,
 "PAR_NOTES" LONGVARCHAR,
 "MRB_CODES" LONGVARCHAR);


